#!/bin/bash

allbackbones=(
    "densenet121"
    "densenet161"
    "resnet50"
    "vgg19"
)

for backbone in ${allbackbones[@]}; do
  python train_backbones.py --backbone $backbone --name $backbone --data-dir /workspace/datasets/cub200_cropped/
done