#!/bin/bash

export dataset_root=/workspace/datasets/cub200_cropped

allbackbones=(
    "densenet161"
    "vgg19"
)
batchsizes=(
    "64"
    "128"
)

for i in ${!allbackbones[@]}; do
  python train_backbones.py \
    --backbone ${allbackbones[i]} \
    --name ${allbackbones[i]}\
    --data-dir $dataset_root \
    --batch-size ${batchsizes[i]}
done

allbackbones=(
    "densenet161"
    "vgg19"
)

for backbone in ${allbackbones[@]}; do
    python train_cbm.py \
        --dataset cub \
        --backbone $backbone \
        --feature_layer features \
        --lam 0.0002 \
        --concept_set "data/concept_sets/cub_filtered_v2.txt" \
        --n_iters 50 \
        --proj_steps 1
done
